from sqlalchemy import MetaData

# Enterprise naming conventions for database constraints.
# This ensures that all indexes, unique constraints, and foreign keys
# generated by SQLAlchemy or Alembic follow a strict, predictable naming pattern.
#
# Examples:
#   Index: ix_user_email
#   Unique: uq_user_email
#   Check: ck_user_age_positive
#   Foreign Key: fk_post_user_id_user
#   Primary Key: pk_user
convention = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

# The global metadata object that all models will attach to.
metadata = MetaData(naming_convention=convention)
