"""Initial MVP Models"""
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa
import app.db.types


# revision identifiers, used by Alembic.
revision: str = 'c5ef64974f42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_insight',
    sa.Column('timestamp', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('target_timeframe', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_insight'))
    )
    op.create_index(op.f('ix_ai_insight_id'), 'ai_insight', ['id'], unique=False)
    op.create_index(op.f('ix_ai_insight_region'), 'ai_insight', ['region'], unique=False)
    op.create_index(op.f('ix_ai_insight_timestamp'), 'ai_insight', ['timestamp'], unique=False)
    op.create_index('ix_ai_insight_timestamp_region', 'ai_insight', ['timestamp', 'region'], unique=False)
    op.create_table('energy_data',
    sa.Column('timestamp', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('value_mw', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_energy_data'))
    )
    op.create_index(op.f('ix_energy_data_id'), 'energy_data', ['id'], unique=False)
    op.create_index(op.f('ix_energy_data_region'), 'energy_data', ['region'], unique=False)
    op.create_index(op.f('ix_energy_data_timestamp'), 'energy_data', ['timestamp'], unique=False)
    op.create_index('ix_energy_data_timestamp_region', 'energy_data', ['timestamp', 'region'], unique=False)
    op.create_table('grid_status',
    sa.Column('timestamp', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('frequency_hz', sa.Float(), nullable=False),
    sa.Column('stability_index', sa.Float(), nullable=False),
    sa.Column('voltage_kv', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grid_status'))
    )
    op.create_index(op.f('ix_grid_status_id'), 'grid_status', ['id'], unique=False)
    op.create_index(op.f('ix_grid_status_region'), 'grid_status', ['region'], unique=False)
    op.create_index(op.f('ix_grid_status_timestamp'), 'grid_status', ['timestamp'], unique=False)
    op.create_index('ix_grid_status_timestamp_region', 'grid_status', ['timestamp', 'region'], unique=False)
    op.create_table('market_data',
    sa.Column('timestamp', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('market_type', sa.String(length=50), nullable=False),
    sa.Column('price_inr', sa.Float(), nullable=False),
    sa.Column('volume_mwh', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_data'))
    )
    op.create_index(op.f('ix_market_data_id'), 'market_data', ['id'], unique=False)
    op.create_index(op.f('ix_market_data_region'), 'market_data', ['region'], unique=False)
    op.create_index(op.f('ix_market_data_timestamp'), 'market_data', ['timestamp'], unique=False)
    op.create_index('ix_market_data_timestamp_region', 'market_data', ['timestamp', 'region'], unique=False)
    op.create_table('weather_data',
    sa.Column('timestamp', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('irradiance_w_m2', sa.Float(), nullable=True),
    sa.Column('wind_speed_m_s', sa.Float(), nullable=True),
    sa.Column('humidity_percent', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_data'))
    )
    op.create_index(op.f('ix_weather_data_id'), 'weather_data', ['id'], unique=False)
    op.create_index(op.f('ix_weather_data_region'), 'weather_data', ['region'], unique=False)
    op.create_index(op.f('ix_weather_data_timestamp'), 'weather_data', ['timestamp'], unique=False)
    op.create_index('ix_weather_data_timestamp_region', 'weather_data', ['timestamp', 'region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weather_data_timestamp_region', table_name='weather_data')
    op.drop_index(op.f('ix_weather_data_timestamp'), table_name='weather_data')
    op.drop_index(op.f('ix_weather_data_region'), table_name='weather_data')
    op.drop_index(op.f('ix_weather_data_id'), table_name='weather_data')
    op.drop_table('weather_data')
    op.drop_index('ix_market_data_timestamp_region', table_name='market_data')
    op.drop_index(op.f('ix_market_data_timestamp'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_region'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_id'), table_name='market_data')
    op.drop_table('market_data')
    op.drop_index('ix_grid_status_timestamp_region', table_name='grid_status')
    op.drop_index(op.f('ix_grid_status_timestamp'), table_name='grid_status')
    op.drop_index(op.f('ix_grid_status_region'), table_name='grid_status')
    op.drop_index(op.f('ix_grid_status_id'), table_name='grid_status')
    op.drop_table('grid_status')
    op.drop_index('ix_energy_data_timestamp_region', table_name='energy_data')
    op.drop_index(op.f('ix_energy_data_timestamp'), table_name='energy_data')
    op.drop_index(op.f('ix_energy_data_region'), table_name='energy_data')
    op.drop_index(op.f('ix_energy_data_id'), table_name='energy_data')
    op.drop_table('energy_data')
    op.drop_index('ix_ai_insight_timestamp_region', table_name='ai_insight')
    op.drop_index(op.f('ix_ai_insight_timestamp'), table_name='ai_insight')
    op.drop_index(op.f('ix_ai_insight_region'), table_name='ai_insight')
    op.drop_index(op.f('ix_ai_insight_id'), table_name='ai_insight')
    op.drop_table('ai_insight')
    # ### end Alembic commands ###
