"""Add analytics tables and columns"""
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa
import app.db.types


# revision identifiers, used by Alembic.
revision: str = 'e81d20401112'
down_revision: Union[str, None] = 'c5ef64974f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carbon_intensity',
    sa.Column('timestamp', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('value_gco2_kwh', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carbon_intensity'))
    )
    op.create_index(op.f('ix_carbon_intensity_id'), 'carbon_intensity', ['id'], unique=False)
    op.create_index(op.f('ix_carbon_intensity_region'), 'carbon_intensity', ['region'], unique=False)
    op.create_index(op.f('ix_carbon_intensity_timestamp'), 'carbon_intensity', ['timestamp'], unique=False)
    op.create_index('ix_carbon_intensity_timestamp_region', 'carbon_intensity', ['timestamp', 'region'], unique=False)
    op.create_table('energy_investments',
    sa.Column('deal_value_inr', sa.Float(), nullable=True),
    sa.Column('investor', sa.String(length=255), nullable=True),
    sa.Column('technology', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_energy_investments'))
    )
    op.create_index(op.f('ix_energy_investments_date'), 'energy_investments', ['date'], unique=False)
    op.create_index(op.f('ix_energy_investments_id'), 'energy_investments', ['id'], unique=False)
    op.create_index(op.f('ix_energy_investments_investor'), 'energy_investments', ['investor'], unique=False)
    op.create_index(op.f('ix_energy_investments_state'), 'energy_investments', ['state'], unique=False)
    op.create_index('ix_energy_investments_tech_state', 'energy_investments', ['technology', 'state'], unique=False)
    op.create_index(op.f('ix_energy_investments_technology'), 'energy_investments', ['technology'], unique=False)
    op.create_table('power_plants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('installed_capacity_mw', sa.Float(), nullable=False),
    sa.Column('fuel_type', sa.String(length=100), nullable=False),
    sa.Column('technology', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_power_plants'))
    )
    op.create_index(op.f('ix_power_plants_fuel_type'), 'power_plants', ['fuel_type'], unique=False)
    op.create_index(op.f('ix_power_plants_id'), 'power_plants', ['id'], unique=False)
    op.create_index(op.f('ix_power_plants_name'), 'power_plants', ['name'], unique=False)
    op.create_index(op.f('ix_power_plants_region'), 'power_plants', ['region'], unique=False)
    op.create_index(op.f('ix_power_plants_state'), 'power_plants', ['state'], unique=False)
    op.create_index('ix_power_plants_state_fuel', 'power_plants', ['state', 'fuel_type'], unique=False)
    op.create_table('power_system_position',
    sa.Column('timestamp', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('peak_demand_mw', sa.Float(), nullable=True),
    sa.Column('energy_met_mu', sa.Float(), nullable=True),
    sa.Column('shortage_mu', sa.Float(), nullable=True),
    sa.Column('frequency_stats', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_power_system_position'))
    )
    op.create_index(op.f('ix_power_system_position_id'), 'power_system_position', ['id'], unique=False)
    op.create_index(op.f('ix_power_system_position_region'), 'power_system_position', ['region'], unique=False)
    op.create_index(op.f('ix_power_system_position_timestamp'), 'power_system_position', ['timestamp'], unique=False)
    op.create_index('ix_psp_timestamp_region', 'power_system_position', ['timestamp', 'region'], unique=False)
    op.create_table('substations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('voltage_kv', sa.Float(), nullable=True),
    sa.Column('capacity_mva', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_substations'))
    )
    op.create_index(op.f('ix_substations_id'), 'substations', ['id'], unique=False)
    op.create_index(op.f('ix_substations_name'), 'substations', ['name'], unique=False)
    op.create_index('ix_substations_voltage', 'substations', ['voltage_kv'], unique=False)
    op.create_table('transmission_lines',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('voltage_kv', sa.Float(), nullable=True),
    sa.Column('circuit_length_km', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transmission_lines'))
    )
    op.create_index(op.f('ix_transmission_lines_id'), 'transmission_lines', ['id'], unique=False)
    op.create_index(op.f('ix_transmission_lines_name'), 'transmission_lines', ['name'], unique=False)
    op.create_index(op.f('ix_transmission_lines_state'), 'transmission_lines', ['state'], unique=False)
    op.create_index('ix_transmission_lines_state_voltage', 'transmission_lines', ['state', 'voltage_kv'], unique=False)
    op.add_column('market_data', sa.Column('mcv_mw', sa.Float(), nullable=True))
    op.add_column('market_data', sa.Column('purchase_bids_mw', sa.Float(), nullable=True))
    op.add_column('market_data', sa.Column('sell_bids_mw', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_data', 'sell_bids_mw')
    op.drop_column('market_data', 'purchase_bids_mw')
    op.drop_column('market_data', 'mcv_mw')
    op.drop_index('ix_transmission_lines_state_voltage', table_name='transmission_lines')
    op.drop_index(op.f('ix_transmission_lines_state'), table_name='transmission_lines')
    op.drop_index(op.f('ix_transmission_lines_name'), table_name='transmission_lines')
    op.drop_index(op.f('ix_transmission_lines_id'), table_name='transmission_lines')
    op.drop_table('transmission_lines')
    op.drop_index('ix_substations_voltage', table_name='substations')
    op.drop_index(op.f('ix_substations_name'), table_name='substations')
    op.drop_index(op.f('ix_substations_id'), table_name='substations')
    op.drop_table('substations')
    op.drop_index('ix_psp_timestamp_region', table_name='power_system_position')
    op.drop_index(op.f('ix_power_system_position_timestamp'), table_name='power_system_position')
    op.drop_index(op.f('ix_power_system_position_region'), table_name='power_system_position')
    op.drop_index(op.f('ix_power_system_position_id'), table_name='power_system_position')
    op.drop_table('power_system_position')
    op.drop_index('ix_power_plants_state_fuel', table_name='power_plants')
    op.drop_index(op.f('ix_power_plants_state'), table_name='power_plants')
    op.drop_index(op.f('ix_power_plants_region'), table_name='power_plants')
    op.drop_index(op.f('ix_power_plants_name'), table_name='power_plants')
    op.drop_index(op.f('ix_power_plants_id'), table_name='power_plants')
    op.drop_index(op.f('ix_power_plants_fuel_type'), table_name='power_plants')
    op.drop_table('power_plants')
    op.drop_index(op.f('ix_energy_investments_technology'), table_name='energy_investments')
    op.drop_index('ix_energy_investments_tech_state', table_name='energy_investments')
    op.drop_index(op.f('ix_energy_investments_state'), table_name='energy_investments')
    op.drop_index(op.f('ix_energy_investments_investor'), table_name='energy_investments')
    op.drop_index(op.f('ix_energy_investments_id'), table_name='energy_investments')
    op.drop_index(op.f('ix_energy_investments_date'), table_name='energy_investments')
    op.drop_table('energy_investments')
    op.drop_index('ix_carbon_intensity_timestamp_region', table_name='carbon_intensity')
    op.drop_index(op.f('ix_carbon_intensity_timestamp'), table_name='carbon_intensity')
    op.drop_index(op.f('ix_carbon_intensity_region'), table_name='carbon_intensity')
    op.drop_index(op.f('ix_carbon_intensity_id'), table_name='carbon_intensity')
    op.drop_table('carbon_intensity')
    # ### end Alembic commands ###
